name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integrate:
    runs-on: ubuntu-latest
    outputs:
      synth-success: ${{ steps.synth.outcome == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      # Disabled test for now
      # - name: Run tests
      #   run: npm test

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Synthesize CloudFormation template
        id: synth
        run: cdk synth

  deploy:
    runs-on: ubuntu-latest
    needs: integrate
    if: needs.integrate.outputs.synth-success == 'success' # Deploy only if synth succeeds

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy CDK Stack
        run: cdk deploy --require-approval never --context stage=${{ github.event_name == 'pull_request' && 'staging' || 'prod' }}
